name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, arm]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake, Ninja and GCC
      uses: lukka/get-cmake@v3.21.1

    # Additional setup for different architectures can be done here

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest
